# Generated by Django 3.2.23 on 2023-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MainDashboard',
            },
        ),
        migrations.CreateModel(
            name='DetailDashboarParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'detail_dashboard',
            },
        ),
    ]
