# Generated by Django 4.1.4 on 2023-03-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EdaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileDef_Data", models.FileField(upload_to="file_store")),
                ("fileLef_Data", models.FileField(upload_to="file_store")),
                ("fileTiming_Data", models.FileField(upload_to="file_store")),
            ],
        ),
        migrations.CreateModel(
            name="Paths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.IntegerField()),
                ("data", models.CharField(max_length=100000)),
            ],
        ),
    ]
