# Generated by Django 5.1 on 2024-09-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MainDashboard',
            },
        ),
        migrations.CreateModel(
            name='DetailDashboarParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('project_name', models.CharField(max_length=100)),
                ('timing_data', models.JSONField()),
            ],
            options={
                'db_table': 'detail_dashboard',
            },
        ),
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
    ]
